[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# https://github.com/netlify/next-runtime/issues/990
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true