name: Release 🚀

on:
  workflow_dispatch:

jobs:
  release:
    name: Release 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          fetch-depth: 0

      - name: Enable node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build packages 🏗️
        run: yarn build

      - name: Deploy docs 📖
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd docs
          npx netlify-cli build
          npx netlify-cli deploy --prod
