name: Deploy Docs

on:
  workflow_dispatch:

jobs:
  release:
    name: Deploy Docs 📖
    runs-on: ubuntu-latest

    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Enable node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build all packages 🏗️
        run: yarn build

      - name: Validate ✅
        run: yarn validate

      - name: Deploy docs 📖
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd docs
          npx netlify-cli build
          npx netlify-cli deploy --prod
