name: 'PR'

on:
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build packages 🏗️
        run: yarn build

      - name: Validate ✅
        run: yarn build

      - name: Danger
        uses: danger/danger-js@11.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
