name: Release 🚀

on:
  workflow_dispatch:

jobs:
  release:
    name: Release 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enable node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build packages 🏗️
        run: yarn build

      - name: Set npm authentication
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Ensure access
        run: npm whoami

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump versions and publish packages 🚀
        run: |
          yarn version:ci
          yarn publish:ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy docs 📖
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          cd docs
          npx netlify-cli build
          npx netlify-cli deploy --prod
